Repository rpopuc/kudos-board, pull requests merged in 2023-04, with the labels that each got.

#2 Feat/create panel route
  .gitignore
  README.md
  docker-compose.override.example.yml
  docker-compose.yml
  docs/http-client.md
  docs/panel.json
  docs/todo.md
  index.ts
  jest.config.ts
  package-lock.json
  package.json
  src/app.ts
  src/controllers/Panel.ts
  src/domains/entities/Panel.ts
  src/domains/useCases/CreatePanel.ts
  src/routes/Panel.ts
  tests/controllers/panel.test.ts
  tests/coverage/.gitignore
  tests/domains/entities/Panel.test.ts
  tests/domains/useCases/CreatePanel.test.ts
Labels: enhancement

#3 chore: create a github actions pipeline for jest tests
  .github/workflows/node-ci.yaml
  docs/todo.md
Labels: enhancement

#16 Create Panel Repository
  docs/todo.md
  package.json
  src/controllers/Panel.ts
  src/domains/Panel/Entities/Panel.ts
  src/domains/Panel/Repositories/PanelRepository.ts
  src/domains/Panel/UseCases/CreatePanel.ts
  src/domains/entities/Panel.ts
  src/domains/useCases/CreatePanel.ts
  tests/controllers/panel.test.ts
  tests/domains/Panel/Repositories/PanelRepository.test.ts
  tests/domains/Panel/entities/Panel.test.ts
  tests/domains/Panel/useCases/CreatePanel.test.ts
  tests/domains/useCases/CreatePanel.test.ts
Labels: enhancement

#14 docs: create logo and add it to readme
  .gitignore
  README.md
  public/logo.png
Labels: documentation

#17 Chore/alias
  jest.config.ts
  package-lock.json
  package.json
  src/app.ts
  src/domains/Panel/Repositories/PanelRepository.ts
  src/domains/Panel/UseCases/CreatePanel.ts
  src/routes/Kudos.ts
  src/routes/Panel.ts
  tests/controllers/panel.test.ts
  tests/domains/Panel/Repositories/PanelRepository.test.ts
  tests/domains/Panel/entities/Panel.test.ts
  tests/domains/Panel/useCases/CreatePanel.test.ts
  tsconfig.json
Labels: enhancement

#19 Chore/lint
  .github/workflows/node-ci.yaml
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
  src/app.ts
  src/domains/Panel/Entities/Panel.ts
  src/domains/Panel/Repositories/PanelRepository.ts
  src/domains/Panel/UseCases/CreatePanel.ts
  tests/controllers/panel.test.ts
  tests/domains/Panel/Repositories/PanelRepository.test.ts
Labels: enhancement

#21 chore: add commit hook to validate code
  package-lock.json
  package.json
  scripts/install.sh
  scripts/pre-commit
Labels: enhancement, chore
