Repository rpopuc/kudos-board, pull requests merged in 2023-07, with the labels that each got.

#86 Use repository interface instead memory in tests
  docs/todo.md
  src/domain/Panel/DTO/UpdatePanelData.ts
  src/domain/Panel/UseCases/UpdatePanel.ts
  tests/domains/Kudos/useCases/ArchiveKudos.test.ts
  tests/domains/Kudos/useCases/UpdateKudos.test.ts
  tests/domains/Panel/useCases/ArchivePanel.test.ts
  tests/domains/Panel/useCases/CreatePanel.test.ts
  tests/domains/Panel/useCases/DeletePanel.test.ts
  tests/domains/Panel/useCases/ShowPanel.test.ts
  tests/domains/Panel/useCases/UpdatePanel.test.ts
Labels: refact

#93 Chore/sanitize mongo types
  docs/todo.md
  src/infra/MongoDB/Repositories/PanelRepository.ts
  src/infra/MongoDB/services/Collection.ts
  src/infra/MongoDB/services/Database.ts
  src/infra/adapters/Express/routes/Panel.ts
  tests/infra/MongoDB/services/Collection.test.ts
  tests/infra/MongoDB/services/Database.test.ts
Labels: enhancement

#94 feat(Kudos): mongodb and controller
  .env.example
  docs/kudos.json
  docs/panel.json
  docs/todo.md
  src/domain/Kudos/Presenters/KudosPresenter.ts
  src/domain/Kudos/Repositories/KudosRepository.ts
  src/domain/Kudos/UseCases/ArchiveKudos.ts
  src/domain/Kudos/UseCases/CreateKudos.ts
  src/domain/Kudos/UseCases/DeleteKudos.ts
  src/domain/Kudos/UseCases/ShowKudos.ts
  src/domain/Kudos/UseCases/UpdateKudos.ts
  src/infra/MongoDB/Repositories/KudosRepository.ts
  src/infra/MongoDB/models/Kudos.ts
  src/infra/adapters/Express/controllers/KudosController.ts
  src/infra/adapters/Express/routes/Kudos.ts
  src/infra/inversify.config.ts
  src/infra/types.ts
  tests/domains/Kudos/useCases/ArchiveKudos.test.ts
  tests/domains/shared/presenters/KudosPresenter.test.ts
  tests/infra/adapters/Express/controllers/kudos.test.ts
Labels: enhancement

#95 fix(Kudos): create routes
  src/infra/adapters/Express/routes/Kudos.ts
Labels: enhancement

#96 Feat/mongodb kudos connection
  src/domain/Kudos/DTO/KudosData.ts
  src/domain/Kudos/Entities/Kudos.ts
  src/infra/MongoDB/Repositories/KudosRepository.ts
  tests/domains/Kudos/useCases/Response/UpdateKudosResponse.test.ts
  tests/domains/Kudos/useCases/UpdateKudos.test.ts
  tests/domains/shared/presenters/KudosPresenter.test.ts
  tests/infra/MongoDB/Repositories/KudosRepository.test.ts
  tests/infra/MongoDB/Repositories/PanelRepository.test.ts
Labels: enhancement

#97 Chore: remove technical debts
  src/domain/Kudos/UseCases/UpdateKudos.ts
  src/domain/Panel/UseCases/UpdatePanel.ts
  src/domain/shared/errors/InvalidStatus.ts
  src/infra/adapters/Express/controllers/PanelController.ts
  tests/domains/Kudos/useCases/UpdateKudos.test.ts
  tests/domains/Panel/useCases/UpdatePanel.test.ts
Labels: chore
